name: 'Help utilize GitHub issue as TODO list'
description: 'You can auto-label to issues according to deadline'
author: 'ikanago'
inputs:
  token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
    required: true
  repository:
    description: 'Repository name in format "OWNER/REPO_NAME"'
    default: ${{ github.repository }}
    required: true
runs:
  using: 'docker'
  image: docker://ghcr.io/ikanago/issue-deadline-manager:0.2.0
  args:
    - ${{ inputs.token }}
    - ${{ inputs.repository }}
branding:
  icon: 'list'
  color: 'green'
