name: 'Help utilize GitHub issue as TODO list'
description: 'You can auto-label to issues according to deadline'
author: 'ikanago'
inputs:
  token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
    required: true
runs:
  using: 'docker'
  image: ghcr.io/ikanago/issue-deadline-manager:main
  args:
    - ${{ inputs.token }}
    - ${{ github.repository }}
branding:
  icon: 'list'
  color: 'green'
