name: Run actions

on:
  pull_request:
    branches:
      - main
      - 'releases/*'

jobs:
  actions:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1

      - name: Build
        run: cargo build --verbose

      - name: Run actions
        run: cargo run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

